### ISSUE TITLE
Website Issues

### ISSUE THREAD

**Issue by DJPlaya** [Arkarr/ASteambot#10]
Same as #9 
Dame it, it just want to gen an Api Key :D
You really should Repair your OS or Webserver Installation

**Comment by DJPlaya** [comment]
NVM, works now again, still it was offline some Mins ago?

**Comment by Arkarr** [comment]
You probably tried to access during his backup time haha... sorry.
Also, the correct address changed : raspberrypimaison.ddns.net/website/public/ASteambot/GetAPIKey/

**Comment by DJPlaya** [comment]
@Arkarr Dont forget to change it in the config.cfg on the next Commit so there wont be more Users wondring ^^

**Comment by Arkarr** [comment]
@DJPlaya yep, it's done!
