### ISSUE TITLE
"Error while downloading the updater"

### ISSUE THREAD

**Issue by DJPlaya** [Arkarr/ASteambot#11]
Error while downloading the updater, aborting update process.
The remote server returned an error: (404) Not Found.

Details:
V 6.7 Public
Win 10 64
Anti Vir Disabled
Windows Firewall disabled
Common Firewall on Router, no UTM

_BTW. The Webinterface Idea wasent that bad_

**Comment by Arkarr** [comment]
Yeah... I am still working on it. I suggest you disable it for now. I need to find a proper way to implement it right now.

Webinterface might not be a bad idea, but I don't have enough time now to also properly implement it and it is not a key feature anyway, so it's pretty much at the bottom of my todo list.

**Comment by DJPlaya** [comment]
I used WyUpdate some time ago, its pretty ugly but it does what it should do (even with the free Version)
> https://wyday.com/wyupdate/

**Comment by Arkarr** [comment]
Yeah, but doesn't run on Linux. I'll get ride of the interface. Thanks!

**Comment by Arkarr** [comment]
Alright, I fixed that issue. I'll push a release this night.
