### ISSUE TITLE
Problem with Country Code Finder

### ISSUE THREAD

**Issue by DJPlaya** [Arkarr/ASteambot#12]
```
ME>Hello
Bot>Sorry, I don't understand your request.
Console>Country "Sankt" not found !
```

I live in "Sankt Augustin" which is in Germany, so i guess the Location you get is a bit too accurate.

**Comment by Arkarr** [comment]
Ha crap! I'll fix it right away.

**Comment by Arkarr** [comment]
Still no fix yet, I know.

**Comment by Arkarr** [comment]
Yeah... it has been a while, But it should be fixed.
