### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by DJPlaya** [Arkarr/ASteambot#13]
```
Unhandled Exception: System.MissingMethodException: Method not found: "Void System.IO.Compression.ZipFileExtensions.ExtractToFile(System.IO.Compression.ZipArchiveEntry, System.String, Boolean)".
   near ASteambot.Program.Main(String[] args)
```
_(I translated some Words from German to English)_

# Details:
Win 2016 Server 64
Pretty Fresh Installation
Tryed without Anti-Vir and Firewall

[DxDiag.txt](https://github.com/Arkarr/ASteambot/files/2645505/DxDiag.txt)

# Runtimes and Similar installed:
.Net Framework 2.0, 3.0, 3.5, 4.6(+Updates)
Java Runtime Environment 8 32/64
DirectX 9.0c Extra files
General runtime files
Microsoft Visual C++ Runtimes (v2005 - v2015)
Microsoft Visual J# 2.0 SE
Adobe Flash Player (Opera, FireFox, Internet Explorer)

**Comment by Arkarr** [comment]
That doesn't make any sense. You download ASteambot from the release, right ?

**Comment by DJPlaya** [comment]
Yea, ive first copied it from my Desktop to the Server, but after that dident worked, i also tried it with the latest release.
Of course ive extracted it and run it as Admin.

Do you want TeamViewer Access for testing it out? I currently do not have any important Files on that Server

**Comment by Arkarr** [comment]
Yeah, I'll check it out.

**Comment by Arkarr** [comment]
Should be fixed.
