### ISSUE TITLE
 Disconnected from Steam, reconnecting in 3 seconds...

### ISSUE THREAD

**Issue by lyskaczu** [Arkarr/ASteambot#15]
Hi I have problem with connection to steam :(

tis is my logs:

`
        Arkarr's Steam profile : http://steamcommunity.com/id/arkarr
*****************************************************************************************************************Searching for updates...
Creating update directory : /root/steambot1
Downloading updater...
Error while downloading the updater, aborting update process.
Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
Username : lyskaczu1  Password : X  API : 67D83DB592**********
Starting TCP server on port 4765
****************************************************************************************************************
Use this ip/port if ASteambot **IS** running on the same machine as the server :
IP : 87.98.218.11 PORT : 4765
Use this ip/port if ASteambot **IS NOT** running on the same machine as the server :
IP : 2001:41d0:1:490b::1 PORT : 4765
  Example (in ASteambot_Core.cfg) :
    sm_asteambot_server_ip "XXX.XXX.XX.XX"
    sm_asteambot_server_port "4765"
****************************************************************************************************************
Got a bad hardware address length for an AF_PACKET 16 8
123546514345-1,-1|0&85568392922695794|87.98.218.11|27015|[PL] Polski-Gaming.pl [DD2] Skiny/Kosy/Rekawiczki FREE / NEW!!!<EOF>
Data :
85568392922695794|87.98.218.11|27015|[PL] Polski-Gaming.pl [DD2] Skiny/Kosy/Rekawiczki FREE / NEW!!!
Connecting to database server...
Success.
Attempt to connect to database...
Connection to database successfully done !
Disconnected from Steam, reconnecting in 3 seconds...
Disconnected from Steam, reconnecting in 3 seconds...
Disconnected from Steam, reconnecting in 3 seconds...
Disconnected from Steam, reconnecting in 3 seconds...
`
I'm testing on two steam accounts with an authentication token and without, where can the problem be?

**Comment by Arkarr** [comment]
First of all, disabled updater. It's not working in his current state.

Now, use the account where there is NO steamguard linked to it.
Then, once the bot started, link this account to steamguard with ASteambot (write 'help' in the console of ASteambot, use the link steamguard command.)

Report results here.

**Comment by Ziome3eg** [comment]
*****************************************************************************************ASteambot - Arkarr's steambot*****************************************************************************************

        All informations related to this software can be found here :
        https://forums.alliedmods.net/showthread.php?t=273091

        Version 8.5 - PUBLIC


        Arkarr's message for you :
        I think it's the first stable version of ASteambot !! <3 ! Thanks so much for debuging it with me !


        I would like you not to remove this text <3 !


        Arkarr's Steam profile : http://steamcommunity.com/id/arkarr
***************************************************************************************************************************************************************************************************************Updater disabled. Not fetching for last updates.
Username : z3gbot  Password : X  API : ********************
Starting TCP server on port 20385
**************************************************************************************************************************************************************************************************************
Use this ip/port if ASteambot **IS** running on the same machine as the server :
IP : **** PORT : 20385
Use this ip/port if ASteambot **IS NOT** running on the same machine as the server :
IP : **** PORT : 20385
  Example (in ASteambot_Core.cfg) :
    sm_asteambot_server_ip "XXX.XXX.XX.XX"
    sm_asteambot_server_port "20385"
**************************************************************************************************************************************************************************************************************
Connecting to database server...
Success.
Attempt to connect to database...
Connection to database successfully done !
Disconnected from Steam, reconnecting in 3 seconds...
Disconnected from Steam, reconnecting in 3 seconds...
Disconnected from Steam, reconnecting in 3 seconds...



I disabled updater and removed guard but no progress, can you help me?

**Comment by Arkarr** [comment]
Did you linked the account to steamguard with ASteambot ?

**Comment by Arkarr** [comment]
@Ziome3eg Can you login to steam with your bot account with your web browser and tell me what do you see there ?
https://store.steampowered.com/twofactor/manage_action

**Comment by Ziome3eg** [comment]
I've got checkeed "Wyłącz Steam Guard	(niezalecane)"
Translated: ""Turn off Steam Guard	(not recomended)"

**Comment by Ziome3eg** [comment]
How do i link account to steamguard with ASteambot when it won't run?

**Comment by Arkarr** [comment]
Well... That's weird. Does your bot account have any ban or something ?

**Comment by Ziome3eg** [comment]
No, just new account that i filled 5$, generated api key and removed guard

**Comment by Ziome3eg** [comment]
I've got files from asteambot.zip on server,unpacked website from zip.

**Comment by Arkarr** [comment]
Can't help you right now.

**Comment by Ziome3eg** [comment]
which script corresponds to connecting to steam? maybe chmod will fix that

**Comment by Arkarr** [comment]
What script? It's an exe. The exe read the config file called config.cfg

**Comment by Arkarr** [comment]
if you have some .auth files, rename them to .auth.old and try again.

**Comment by Ziome3eg** [comment]
I have nothing :/ It won't work on Debian 8 vps and Ubuntu 16.04 vps

**Comment by Arkarr** [comment]
What did you tried so far ?
Try this :
1) Download ASteambot for the release tab on github
2) Create a new steam account, don't use the one you tried before
3) Edit config.cfg with the details of the new account
4) Post the results
