### ISSUE TITLE
Erro on startup [Couldn't download the last release.]

### ISSUE THREAD

**Issue by NATroutter** [Arkarr/ASteambot#18]
When i'm trying to run ASteambot this happens
[https://i.imgur.com/Rniwh4f.png](https://i.imgur.com/Rniwh4f.png)

**Comment by Arkarr** [comment]
Weird, I'll check it out. Disable auto-updater for now (using the config.cfg file.)

I'll update tonight.

**Comment by Arkarr** [comment]
![image](https://user-images.githubusercontent.com/4703530/56666391-19840000-66ac-11e9-8bc4-e1c4593c1d2d.png)
Could NOT reproduce the bug.

**Comment by Arkarr** [comment]
I am stupid. I found the bug. Fixing it now.

**Comment by Arkarr** [comment]
Herm.. I found the bug, I tested it, fixed it, but forgot to fix it. Will do tonight.
