### ISSUE TITLE
[Feature Request] Auto remove Friends

### ISSUE THREAD

**Issue by DJPlaya** [Arkarr/ASteambot#2]
Since Steam limits the Amount of Friends we can have, the Bot should Auto detect its max Friends and always leave 1 Slot free. When someone new adds him, he auto removes the oldest Friend.

Calculating the max. Friends is pretty easy: By default there is a Limit of 250 Friends, +5 Slots per Level

**Comment by Arkarr** [comment]
Sounds like a good idea, I'll do that.
