### ISSUE TITLE
Start failed

### ISSUE THREAD

**Issue by hadesownage** [Arkarr/ASteambot#20]
Hello, I can't start the bot on Ubuntu 18.04, I followed the instructions like in video.

`Log file (SEND_TO_ARKARR.log) generated ! Send it to Arkarr !!
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'ASteambot.Config' from assembly 'ASteambot, Version=1.1.1.1, Culture=neutral, PublicKeyToken=null'.
  at ASteambot.Program.Main (System.String[] args) [0x0002e] in <abc33f0d35c34a60bddfc466744ec414>:0 `

**Comment by Arkarr** [comment]
Thanks, fixed. Download Last release.
