### ISSUE TITLE
Website is not working

### ISSUE THREAD

**Issue by srkhost** [Arkarr/ASteambot#23]
Hello,

also the website is not working,

http://raspberrypimaison.ddns.net/asteambot/GetAPIKey/
404

**Comment by Arkarr** [comment]
yeah, I know. It's not useful for now anyway. I lost it when I lost my server. I'll rebuild it once.

**Comment by Arkarr** [comment]
http://arkarrsourceservers.ddns.net/website/public/ASteambot/apikey/
