### ISSUE TITLE
Bot removes friends on startup

### ISSUE THREAD

**Issue by dominik0207** [Arkarr/ASteambot#26]
Hello,

every time on startup the Bot removes all friends except one (my account).
First I thought it was just my modified version of your bot but after I tested it with your last release, the same things happened.
I can add friends and they will stay on the friendslist but after restart they will be removed.

I hope you have an idea what it could be.

greetings Dominik

**Comment by Arkarr** [comment]
Weird. It doesn't do that to me. What version are you using ? Starting from V11.X it should display more informations about friend request.

**Comment by dominik0207** [comment]
I fixed the problem. It seems that it is a "problem" from steam. If I didn't write a message to the bot with a newly added friend, it wouldn't be registered as friend. So they were removed after a restart.

Thank you anyway ^^

**Comment by Arkarr** [comment]
Interesting. I'll check it out.
