### ISSUE TITLE
No servers connected to me :'( !

### ISSUE THREAD

**Issue by cmer81** [Arkarr/ASteambot#28]
Hello,

I can't list my (3) servers from the bot.

![Capture-20200521042745-912x387.png](https://www.heberger-image.fr/images/2020/05/21/Capture-20200521042745-912x387.png)

2 csgo server from windows server 2019
1 csgo server on docker linux

the bot works correctly

[![Capture-20200521041120-897x345.png](https://www.heberger-image.fr/images/2020/05/21/Capture-20200521041120-897x345.png)](https://www.heberger-image.fr/image/UdUe)

```
[SM] Plugin [ANY] ASteambot Core reloaded successfully.
ASteambot : DEBUG MODE IS 'OFF'
[ASteambot - Core] - Attempt to connect to xxx.xxx:4768 ...
[ASteambot - Core] - CONNECTED to ASteambot.
```

no firewall between servers [STEAMBOT] <===> [CSGO]

same problem with installation steambot on linux and windows 🤯

![Capture-20200521044623-826x78.png](https://www.heberger-image.fr/images/2020/05/21/Capture-20200521044623-826x78.png)

can you help me please ?

**Comment by Arkarr** [comment]
Hi, sorry for the delay. I am a bit busy those days.

Yes, this usually happens because you have a firewall preventing connection and those ports.

You can add me on Steam, I belive I do speak your language, it will be easier to solve it together there, I will then post later the fix here.

**Comment by cmer81** [comment]
thank you for the answer!!
i added you on steam, account request cmer.

**Comment by Arkarr** [comment]
Probleme solved. TCP password wasn't the same on config.cfg and ASteambot_Core.cfg.
