### ISSUE TITLE
Linux error 

### ISSUE THREAD

**Issue by Draakoor** [Arkarr/ASteambot#29]
[SEND_TO_ARKARR.log](https://github.com/Arkarr/ASteambot/files/4666517/SEND_TO_ARKARR.log)
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not set up parent class, due to: assembly:/home/steam/gameserver/steambot/System.Private.CoreLib.dll type:Object member:(null)
at ASteambot.Config.LoadConfig () [0x000d2] in :0
at ASteambot.Program.Start () [0x0002f] in :0
at ASteambot.Program.Main (System.String[] args) [0x0002e] in :0
SEND_TO_ARKARR.log

Using the latest mono on debian
I can't reopen the last issue sry

**Comment by Arkarr** [comment]
No worries, don't use mono. ASteambot doesn't need mono anymore. Use netcore instead.
https://dotnet.microsoft.com/download/dotnet-core

You can auto-install the requirement and ASteambot via the provided script (check Alliedmodders on main thread of ASteambot).

**Comment by Arkarr** [comment]
#27
