### ISSUE TITLE
Send To Arkarr (LeL ^^)

### ISSUE THREAD

**Issue by DJPlaya** [Arkarr/ASteambot#3]
-Latest Version
Log > https://pastebin.com/AAbqRa7L
CFG > https://pastebin.com/8PD5JKki

Suggestion:
The default "database_port" in the Config is 3306
The default "TCP_ServerPort" is 4765 as suggested in the Description

**Comment by Arkarr** [comment]
What's the status of SteamGuard on your bot's account ?

**Comment by DJPlaya** [comment]
Steam Guard is Activated with Mobile Auth
Community Ban | In good standing
Trade Ban | In good standing

**Comment by Arkarr** [comment]
Strange. I'll look at it in version 1.9.X

**Comment by Arkarr** [comment]
Fixed ! I believe.
