### ISSUE TITLE
Website is gone

### ISSUE THREAD

**Issue by samdisk11** [Arkarr/ASteambot#31]
the website (and its api key generator) is gone.
how do i acquire another api key?

**Comment by Arkarr** [comment]
The website ain't gone. What URL are you using ?

**Comment by samdisk11** [comment]
http://raspberrypimaison.ddns.net/website/public/ASteambot/ ?

**Comment by Arkarr** [comment]
http://arkarrsourceservers.ddns.net/website/public/ASteambot/
