### ISSUE TITLE
High CPU usage (v1.8)

### ISSUE THREAD

**Issue by M-archand** [Arkarr/ASteambot#4]
Hey there, was testing this out today on my local machine (i7-6700k @ 4.8ghz) and I seem to have set it up properly according to the cmd line. My only issue is that once it logs in successfully it uses 92-97% of my CPU and completely bricks my computer. Not running any extra modules on it, just the core.

**Comment by Arkarr** [comment]
Yeah, V1.8.0 is know to be full of bugs. For now, I suggest you to use an older version. 1.7.3 for exemple, you should wait for an update, sorry :( !

**Comment by M-archand** [comment]
Thanks for the update! Using 1.7.3, no cpu usage on idle and 21mb of ram, much better :D
