### ISSUE TITLE
Disconnected problem

### ISSUE THREAD

**Issue by MissXecutioner** [Arkarr/ASteambot#40]
![image](https://user-images.githubusercontent.com/73059032/127389841-bdc2a24f-2b4a-42b2-880a-8eb7efb59d1d.png)

**Comment by MissXecutioner** [comment]
![image](https://user-images.githubusercontent.com/73059032/127785031-c8004d7a-fe5e-4f5e-a8fe-fa5388f846ea.png)

**Comment by Arkarr** [comment]
Alright.

So the first screenshot indicate that you are loosing connection to Steam server.
This could be either on your end, or on Steam end.

Check that you always have internet connection and that nothing is communication on the same port as ASteambot. It's not a big deal through. The bot should always be available and as soon as it disconnect, it will reconnect, as shown in the first screenshot as well.

Second 'error' is more of a warning for me. I forgot to get ride of this message. I'll remove the big scary red text and replace it with a yellow one.

This warning indicate that it can't find the language based on the country name of the user profile (for translation support).

You can ignore that as well.
