### ISSUE TITLE
Market scan connection refused problem

### ISSUE THREAD

**Issue by MissXecutioner** [Arkarr/ASteambot#41]
![image](https://user-images.githubusercontent.com/73059032/127785185-9a40959f-719a-42aa-b6c7-a797e5c983ce.png)

**Comment by Arkarr** [comment]
Hey,

Yes, I am aware of this. You can ignore that error, it's my raspberry PI rebooting from time to time. I'll move that to another, more stale machine. But hey, I need money haha..
