### ISSUE TITLE
C.Refused problem :/

### ISSUE THREAD

**Issue by MissXecutioner** [Arkarr/ASteambot#43]
![image](https://user-images.githubusercontent.com/73059032/132405385-375b9fe4-c06b-4e09-970c-8024143601c4.png)

**Comment by MissXecutioner** [comment]
up

**Comment by MissXecutioner** [comment]
up

**Comment by Arkarr** [comment]
Yes, sorry. I am back. This issue is on my end, you can safely ignore it. I'm working on a large update to help user better understand why this and that is happening.
